# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.network :private_network, ip: "172.16.0.100"
    config.vm.synced_folder "./shared", "/shared", create: true

    config.ssh.forward_agent = true
    
    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false        
    end

    config.vm.provider :virtualbox do |vb|
        # Use VBoxManage to customize the VM. For example to change memory:
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.customize ["modifyvm", :id, "--memory", "4096"]
    end

    
    config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
            host_ip_address: `ifconfig en0| grep "inet " | awk '{printf "%s", $2}'`
        }
        ansible.playbook = "provision/vagrant.yml"
    end
  
    config.vm.provision :shell, :inline => "rm /etc/localtime && ln -s /usr/share/zoneinfo/America/New_York /etc/localtime && ntpdate pool.ntp.org"

end
